### ISSUE TITLE
NameError: name 'raw_input' is not defined 

### ISSUE THREAD

**Issue by 6a6ygd** [LionSec/katoolin#306]
I installed the program just fine but when I try to launch it, I am met with this message and I do not know how to fix it. I am running Arch Linux in Virtual Box if that helps. 

Traceback (most recent call last):
  File "/usr/bin/katoolin", line 1294, in main
    inicio1()
  File "/usr/bin/katoolin", line 41, in inicio1
    opcion0 = raw_input("\033[1;36mkat > \033[1;m")
NameError: name 'raw_input' is not defined

![Screenshot from 2021-12-07 10-44-19](https://user-images.githubusercontent.com/95703185/145060663-5a38c88c-d26d-42fb-96af-4aa70e1a4b87.png)

**Comment by 6a6ygd** [comment]
I fixed it. I used nano to edit line 1294 and line 41 from saying raw_input to saying input. apparently raw_input() was renamed to input() in python3. Anyways I just edited those lines of code and I've got it working just fine now.
