### ISSUE TITLE
Why am I getting this error while executing katoolin 

### ISSUE THREAD

**Issue by Jagath918** [LionSec/katoolin#313]
Traceback (most recent call last):
  File "/home/anon/katoolin/./katoolin.py", line 1294, in main
    inicio1()
  File "/home/anon/katoolin/./katoolin.py", line 41, in inicio1
    opcion0 = raw_input("\033[1;36mkat > \033[1;m")
NameError: name 'raw_input' is not defined

**Comment by aiyer-commits** [comment]
are you using python3 or python2.7?

**Comment by Jagath918** [comment]
> are you using python3 or python2.7?

Python3 in fedora distro

**Comment by nathmo** [comment]
i've made a fork that works if you did not managed to make it work. 

https://github.com/nathmo/katoolin/blob/master/README.md

**Comment by Abdul-Manan-C** [comment]
Same issue using python 3 in fedora and getting error at last opening process

**Comment by nathmo** [comment]
Hi, this script only works for debian baswd distribution as it install package using aptitude. Fedora doesnt use apt to install package
