### ISSUE TITLE
error line 58 fixed but line 41 and 1294 issues

### ISSUE THREAD

**Issue by Toni500github** [LionSec/katoolin#317]
after i have added at line 58 the (), another problem appeard
┌──(kali㉿kali)-[~]
└─$ sudo katoolin
  File "/usr/bin/katoolin", line 8
    print "Sorry. This script requires sudo privledges"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Sorry. This script requires sudo privledges")?
                                                                             
┌──(kali㉿kali)-[~]
└─$ sudo katoolin

 $$\   $$\             $$\                         $$\ $$\           
 $$ | $$  |            $$ |                        $$ |\__|          
 $$ |$$  /  $$$$$$\  $$$$$$\    $$$$$$\   $$$$$$\  $$ |$$\ $$$$$$$\  
 $$$$$  /   \____$$\ \_$$  _|  $$  __$$\ $$  __$$\ $$ |$$ |$$  __$$\ 
 $$  $$<    $$$$$$$ |  Kali linux tools installer |$$ |$$ |$$ |  $$ |
 $$ |\$$\  $$  __$$ |  $$ |$$\ $$ |  $$ |$$ |  $$ |$$ |$$ |$$ |  $$ |
 $$ | \$$\ \$$$$$$$ |  \$$$$  |\$$$$$$  |\$$$$$$  |$$ |$$ |$$ |  $$ |        
 \__|  \__| \_______|   \____/  \______/  \______/ \__|\__|\__|  \__| V2.0   

 + -- -- +=[ Author: LionSec, updated by nathmo
 + -- -- +=[ 331 Tools                                                       

[W] Before updating your system , please remove all Kali-linux repositories to avoid any kind of problem .                                                

1) Add Kali repositories & Update 
2) View Categories
3) Install classicmenu indicator
4) Install Kali menu
5) Help

Traceback (most recent call last):
  File "/usr/bin/katoolin", line 1294, in main
    inicio1()
  File "/usr/bin/katoolin", line 41, in inicio1
    opcion0 = raw_input("\033[1;36mkat > \033[1;m")
NameError: name 'raw_input' is not defined

**Comment by Toni500github** [comment]
![Screenshot 2022-05-01 12_15_21](https://user-images.githubusercontent.com/88878648/166154791-1fc5663f-fde9-4a5e-8123-e8442e8017a2.png)

**Comment by RobertW2** [comment]
Have this issue as well.

**Comment by nathmo** [comment]
i might recommend you this issue https://github.com/LionSec/katoolin/issues/315 that could help you save your problem. 
and if you choose to convert the script to python3 you can make a pull request to my repo. i will be glad to add it
