### ISSUE TITLE
I get this error when trying to install on Fedora 37

### ISSUE THREAD

**Issue by 0797cjm** [LionSec/katoolin#341]
![image](https://user-images.githubusercontent.com/24609015/212574718-ba8186cf-5c5f-4ce0-8f60-881c4c784a17.png)
`
[root@fedora /]# sudo katoolin

 $$\   $$\             $$\                         $$\ $$\           
 $$ | $$  |            $$ |                        $$ |\__|          
 $$ |$$  /  $$$$$$\  $$$$$$\    $$$$$$\   $$$$$$\  $$ |$$\ $$$$$$$\  
 $$$$$  /   \____$$\ \_$$  _|  $$  __$$\ $$  __$$\ $$ |$$ |$$  __$$\ 
 $$  $$<    $$$$$$$ |  Kali linux tools installer |$$ |$$ |$$ |  $$ |
 $$ |\$$\  $$  __$$ |  $$ |$$\ $$ |  $$ |$$ |  $$ |$$ |$$ |$$ |  $$ |
 $$ | \$$\ \$$$$$$$ |  \$$$$  |\$$$$$$  |\$$$$$$  |$$ |$$ |$$ |  $$ |
 \__|  \__| \_______|   \____/  \______/  \______/ \__|\__|\__|  \__| V2.0 

 + -- -- +=[ Author: LionSec | Homepage: www.neodrix.com
 + -- -- +=[ 331 Tools 

[W] Before updating your system , please remove all Kali-linux repositories to avoid any kind of problem .
		

1) Add Kali repositories & Update 
2) View Categories
3) Install classicmenu indicator
4) Install Kali menu
5) Help

			
Traceback (most recent call last):
  File "/usr/bin/katoolin", line 1294, in main
    inicio1()
  File "/usr/bin/katoolin", line 41, in inicio1
    opcion0 = raw_input("\033[1;36mkat > \033[1;m")
              ^^^^^^^^^
NameError: name 'raw_input' is not defined

`

**Comment by bahesh** [comment]
I got this error too ( i believe its meant for any other distro than Debian based . because when i checked the script , it was using apt repository)

**Comment by bahesh** [comment]
![image](https://user-images.githubusercontent.com/76744429/220114509-de47c06d-6a81-46f8-8ae5-c3f8ec158c29.png)
this is how i get it when i return (Do note that i am using an updated version of this same script , https://github.com/cerealkiller1918/katoolin )

**Comment by keys-i** [comment]
it is not a error, raw_input() was renamed to input() in python v3.x

**Comment by 0797cjm** [comment]
How do we fix it

**Comment by ghost** [comment]
go to file , if you use nano
go to the dir where the file is , open terminal 
nano (file.name)
then replace  raw_input by input 
it will work just fine
