### ISSUE TITLE
Python error on Arch Linux (Manjaro)

### ISSUE THREAD

**Issue by DrDrakhan** [LionSec/katoolin#71]
Idk what to say, its just weird...

Traceback (most recent call last):
  File "/usr/bin/katoolin", line 1290, in main
    inicio1()
  File "/usr/bin/katoolin", line 37, in inicio1
    opcion0 = raw_input("\033[1;36mkat > \033[1;m")
NameError: name 'raw_input' is not defined
[manjaro katoolin-master]#

**Comment by solinium** [comment]
It's possible you're running it on the wrong python version? I believe raw_input() was renamed to input() python3, correct me if I'm wrong. Try running it in python2.7?

**Comment by powpowlk** [comment]
I think that you also will need to modify the script, because manjaro inherits- pacman as package manager and the script uses apt-get from debian.In addition, you should search if the packages to install are in the officials repositories or aur.

**Comment by solinium** [comment]
@powpowlk You're absolutely right, I didn't even think about the fact that he was on manjaro. For anyone who is interested in using kali tools on non-debian/ubuntu based distros remember that kali is just slightly modified debian so there is no guarantee all of the tools will work on other distros.

**Comment by firmianay** [comment]
You can try Blackarch, a penetration testing distribution like Kali but Arch linux based. Just install its tools on the Manjaro. I called it Black Manjaro :)
https://github.com/firmianay/Life-long-Learner/blob/master/use-Linux/arch-linux.md#black-manjaro-install-blackarch-tools

**Comment by 6a6ygd** [comment]
I just used nano to edit the /usr/bin/katoolin file and edited line 1294 and line 41 to use input instead of raw_input and I've got it working just fine now
